config/routes.rb
Rails.application.routes.draw do

  root  'welcome#index'

  resources :users do 
    member do
      get :followers
      get :followees
      get :tweets
      get :email
    end
  end
  resources :sessions
  resources :welcome
  resources :tweets
  resources :followings

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  post 'follow' => 'followings#create'
  delete 'unfollow' => 'followings#destroy'
  get 'register' => 'users#new'
  post 'users/find' => 'users#find', as: 'find_users'
end

app/models/following.rb
class Following < ActiveRecord::Base
	belongs_to :user
  belongs_to :followee, :class_name => 'User'
  belongs_to :follower, :class_name => 'User'

  validates :follower_id, presence: true, numericality: { only_integer: true}
  validates :followee_id, presence: true, numericality: { only_integer: true }
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :tweet

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
	belongs_to :user
  has_many :likes

  validates :body, presence: true, length: { maximum: 140 }
end

app/models/user.rb
class User < ActiveRecord::Base
	include BCrypt

  mount_uploader :avatar, AvatarUploader
  
	has_many :followings_as_follower, :class_name=> "Following", foreign_key: :follower_id
  has_many :followings_as_followee, :class_name=> "Following", foreign_key: :followee_id

  has_many :followers, :through => :followings_as_followee
  has_many :followees, :through => :followings_as_follower

  has_many :tweets

  before_save { self.email = email.downcase }
  validates :first_name, :last_name, :first_name_en, :last_name_en, :email, :username,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  # validates :password, confirmation: true, presence: true, length: { minimum: 6 }
  
  def avatar_url
    if self.avatar.url.nil?
      return "/avatar.png"
    else
      return self.avatar.url
    end
  end

  def follow(other_user)
  	followees << other_user
  end
  
  def unfollow(other_user)
  	followees.delete(other_user)
  end

  def following?(other_user)
  	folloing.include?(other_user)
  end	

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def authenticate_admin
    unless current_user && current_user.admin
      flash[:error] = "You are not an admin"
      redirect_to '/'
    end
  end
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
	def new 
    @following = Following.new
	end
	def create
		@following = Following.new(follower_id: params[:follower], followee_id: params[:followee])

		if @following.save
      # flash[:success] = "已成功追蹤此使用者"
      redirect_to root_path
    else
      # flash[:error] = "無法完成追蹤要求"
      redirect_to request.referrer
    end
	end

	def destroy
  	@following = Following.find_by(follower_id: params[:follower], followee_id: params[:followee])
  	@following.destroy
  	redirect_to request.referrer
	end
	
	private
	def following_params
	params.require(:following).permit(:follower_id, :followee_id)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include ApplicationHelper

  def new
  end

  def create
    login
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
	end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
	def new
		@tweet = Tweet.new
		@user = current_user
	end

	def create
		@tweet = Tweet.new(tweet_params)
    if @tweet.save
      flash[:success] = "貼文已發佈"
      redirect_to root_path
    else
      flash[:error] = "基於某些原因貼文尚未發布，請稍後再試"
      redirect_to new_tweet_path
    end
	end
	
	def destroy
		@tweet = Tweet.find(params[:id])
		@tweet.destroy
		redirect_to request.referer
	end

	private
	def tweet_params
    params.require(:tweet).permit(:user_id, :body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        flash[:success] = "成功註冊新使用者"
        format.html { redirect_to @user}
        format.json { render :show, status: :created, location: @user }

      else
        flash[:error] = "資料不完整或有誤"
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }

      end
    end
  end

  def show
    @user = User.find(params[:id])
    @tweets = @user.tweets
    # render edit_user_path
  end

  def edit
    if current_user.id.to_s == params[:id]
      @user = current_user
    else
      redirect_to user_path
    end
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to user_path
    else
      flash[:error] = "暫時無法完成上傳"
      redirect_to user_path
    end
  end

  def find
    @q = params[:query]
    @user = User.where("username LIKE ? or email LIKE ?", @q, @q)
    # @user = User.find_by(username: params[:query])
    if @user.present?
      redirect_to user_path(@user.first.id)
      # using where method returns an array of model
    else
      flash[:error] = "找不到使用者"
      # redirect_to user_path(current_user.id)
      redirect_to request.referer
    end
  end

  def followers
    @user = User.find(params[:id])
    @followees = @user.followees
    @followers = @user.followers
  end

  def followees
  	@user = User.find(params[:id])
    @followees = @user.followees
    @followers = @user.followers
  end

  def tweets
    @user = User.find(params[:id])
    @tweets = @user.tweets
  end

  def email
    @user = User.find(params[:id])
    if @user == current_user
      if @user.itf.present? && @user.utr.present? && @user.gpa.present? && @user.skype.present? && @user.country.present? && @user.sat.present? && @user.toefl.present? && @user.act.present?
        @itf = @user.itf.to_s
        @utr = @user.utr.to_s
        @gpa = @user.gpa.to_s
        @sat = @user.sat.to_s
      else
        redirect_to user_path(@user)
        flash[:error] = "你的資料還不夠齊全喔"
      end
    else
      redirect_to user_path(@user)
      flash[:error] = "只有帳號擁有者才看得到喔"
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :first_name, :last_name, :email, :password, :avatar, :itf, :utr, :ntr, :righthanded, :double_handed_backhand, :height, :weight, :sat, :toefl, :act, :birthday, :about, :first_name_en, :last_name_en, :gpa, :academy, :country, :city, :skype)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@user=current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def login
    user = User.find_by(username: params[:session][:username])
    if user == nil
      flash[:fail] = "Username or password incorrect."
      redirect_to new_session_path
    elsif user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      if user.admin
        redirect_to '/admin'
      else
        redirect_to root_path
      end
    else
      flash[:fail] = "Username or password incorrect."
      redirect_to new_session_path
    end
  end

  # def logged_in
  #   session[:user_id] ? true : false
  # end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %link{href: "http://fonts.googleapis.com/icon?family=Material+Icons", rel: "stylesheet"}
    %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/materialize/0.99.0/css/materialize.min.css", :rel => "stylesheet"}
    / Compiled and minified JavaScript
    %link{:href => "https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700", :rel => "stylesheet"}
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title LinkSport
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    = render '/nav'
    = render '/flash'
    = yield
    %script{:src => "https://cdnjs.cloudflare.com/ajax/libs/materialize/0.99.0/js/materialize.min.js"}
    %script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"}
    / Compiled and minified CSS

app/views/tweets/new.html.haml
%div.card-panel.teal.lighten-3.center-align.register-form
  = form_for @tweet do |f|
    %p
      = f.label :body, "你在想什麼"
      = f.text_field :body
      = f.hidden_field :user_id, value: @user.id
    %a.waves-effect.waves-light.btn
      = f.submit "發送新文章"

app/views/users/edit.html.haml
.section{:class => "edit-page"}
	%div.edit-user-avatar
		=image_tag @user.avatar_url, class: "materialboxed"
	= form_for @user do |f|
		.row
			%form.col.s12
				.row.center
					= f.label :avatar, "個人照片"
					= f.file_field :avatar
				.row
					.input-field.col.s4
						=f.label :first_name, "名"
						=f.text_field :first_name
					.input-field.col.s4
						=f.label :last_name, "姓"
						=f.text_field :last_name
					.input-field.col.s4
						=f.label :email, "信箱"
						=f.text_field :email
				.row
					.input-field.col.s6
						=f.label :height, "身高"
						=f.text_field :height
					.input-field.col.s6
						=f.label :weight, "體重"
						=f.text_field :weight
				.row
					.input-field.col.s3
						=f.label :sat, "SAT"
						=f.text_field :sat
					.input-field.col.s3
						=f.label :act, "ACT"
						=f.text_field :act
					.input-field.col.s3
						=f.label :toefl, "TOEFL"
						=f.text_field :toefl
					.input-field.col.s3
						=f.label :gpa, "GPA"
						=f.text_field :gpa
				.row
					.input-field.col.s4
						=f.label :skype, "Skype"
						=f.text_field :skype
					.input-field.col.s4
						=f.label :first_name_en, "英文名"
						=f.text_field :first_name_en
					.input-field.col.s4
						=f.label :last_name_en, "英文姓"
						=f.text_field :last_name_en
				.row
					.input-field.col.s4
						=f.label :academy, "訓練單位"
						=f.text_field :academy
					.input-field.col.s4
						=f.label :country, "國家"
						=f.text_field :country
					.input-field.col.s4
						=f.label :city, "城市"
						=f.text_field :city
				.row
					.input-field.col.s4
						=f.label :itf, "ITF 排名"
						=f.text_field :itf
					.input-field.col.s4
						=f.label :utr, "Universal Tennis Rating"
						=f.text_field :utr
					.input-field.col.s4
						=f.label :ntr, "全國排名"
						=f.text_field :ntr
				.row
					.input-field.col.s12
						%i.material-icons.prefix mode_edit
						=f.label :about, "關於我"
						=f.text_area :about, class: 'materialize-textarea'
				/ .row
				/ 	.input-field.col.s12
				/ 		=f.label :created_at, "加入日期"
				/ 		=f.text_field :created_at, disabled: "diabled"
				.row
					.input-field.col.s3
						=f.radio_button :righthanded, false, :checked => true, value: false, class: "with-gap"
						=f.label :righthanded, "左手持拍", value: false, name: "group1"
						=f.radio_button :righthanded, true, value: true, class: "with-gap"
						=f.label :righthanded, "右手持拍", value: true, name: "group1"
					.input-field.col.s3
						=f.radio_button :double_handed_backhand, false, :checked => true, value: false, class: "with-gap"
						=f.label :double_handed_backhand, "單手反拍", value: false, name: "group2"
						=f.radio_button :double_handed_backhand, true, value: true, class: "with-gap"
						=f.label :double_handed_backhand, "雙手反拍", value: true, name: "group2"
			%a.waves-effect.waves-light.btn.col.s6.center-align
				= f.submit
	
/		    .row
/		      .col.s12
/		        This is an inline input field:
/		        .input-field.inline
/		          %input#email.validate{:type => "email"}/
/		          %label{"data-error" => "wrong", "data-success" => "right", :for => "email"} Email

app/views/users/email.html.haml
%div.container
	%div#content
		%p
			= "Dear Coach, This is " + @user.first_name_en + " " + @user.last_name_en + " from " + @user.country + ", and I am aspiring to play inter-collegiate tennis in the U.S. My highest ITF career ranking was " + @itf + " and my UTR is " + @utr + ". I am currently being trained at " + @user.academy +  " which has a really international and professional team composed of top players from different countries and eminent coaches providing a thorough physical analysis and tennis program. Therefore, I would love to further develop my interests in strength training, computer science and business in college. For your reference, the link below is a highlight video of my playing at Taiwan National game:https://youtu.be/j8YOBjCok2U Regarding of my academic performance, my GPA was " + @gpa + ", and I scored an " + @sat + " out of 1600 on my SAT. I would like to politely ask you if I have any chance to be a part of your team in the fall of 2018. I am willing to answer any further questions you may have, so please don't hesitate to contact me. I can be reached by " + @user.email + ", and my head coach Tom Kindavong can be reached bykindavongtom@hotmail.com Thank you so much for your time and I look forward to talking to you via Skype (ID: " + @user.skype + ") very soon. To see more of my information please go to"
			%a{href:"https://www.hankchentennis.com"} My profile
			%p
				= "Sincerely, Han-Yu Chen/ Athlete Email: " + @user.email + " Skype: " + @user.skype
	.btn.blue.copy{onclick:"copyToClipboard('#content')"}
		%i.material-icons assignment
		複製


	/ and I have won the championship of the 2015 National High School Athletic Games in Taiwan.

app/views/users/followees.html.haml
%section.followers
  %ul#tabs-swipe-demo.tabs
    %li.tab.col.s3
      %a{:href => "#test-swipe-1"}
        = @user.followees.count
        追蹤中
    %li.tab.col.s3
      %a{:href => "#test-swipe-2"}
        = @user.followers.count
        粉絲
  #test-swipe-1.col.s12.white
    %ul
      - @followees.each do |followee|
        %li.followers-list 
          =link_to image_tag(followee.avatar_url), user_path(followee), class: "follower-avatar"
          %div.follower-href
            = link_to followee.last_name + followee.first_name, user_path(followee), class: "follwer-name"
            = link_to followee.about || "", user_path(followee), class: "follower-about"
        %li.divider
  #test-swipe-2.col.s12.white
    %ul
      - @followers.each do |follower|
        %li.followers-list 
          =link_to image_tag(follower.avatar_url), user_path(follower), class: "follower-avatar"
          %div.follower-href
            = link_to follower.last_name + follower.first_name, user_path(follower), class: "follwer-name"
            = link_to follower.about || "", user_path(follower), class: "follower-about"
          %li.divider

app/views/users/followers.html.haml
%section.followers
  %ul#tabs-swipe-demo.tabs
    %li.tab.col.s3
      %a{:href => "#test-swipe-1"}
        = @user.followees.count
        追蹤中
    %li.tab.col.s3
      %a.active{:href => "#test-swipe-2"}
        = @user.followers.count
        粉絲
  #test-swipe-1.col.s12.white
    %ul
      - @followees.each do |followee|
        %li.followers-list 
          =link_to image_tag(followee.avatar_url), user_path(followee), class: "follower-avatar"
          %div.follower-href
            = link_to followee.last_name + followee.first_name, user_path(followee), class: "follwer-name"
            = link_to followee.about || "", user_path(followee), class: "follower-about"
        %li.divider
  #test-swipe-2.col.s12.white
    %ul
      - @followers.each do |follower|
        %li.followers-list 
          =link_to image_tag(follower.avatar_url), user_path(follower), class: "follower-avatar"
          %div.follower-href
            = link_to follower.last_name + follower.first_name, user_path(follower), class: "follwer-name"
            = link_to follower.about || "", user_path(follower), class: "follower-about"
          %li.divider

app/views/users/new.html.haml
%div.card-panel.teal.lighten-3.center-align.register-form
  -# - if @user.errors.any?
  -#   #error_explanation
  -#     %h2.error
  -#       = pluralize(@user.errors.count, "error")
  -#       prohibited
  -#       this user from being saved:
  -#     %ul.error
  -#       - @user.errors.full_messages.each do |msg|
  -#         %li= msg
  = form_for @user do |f|
    %p
      = f.label :last_name, "姓"
      = f.text_field :last_name
    %p
      = f.label :first_name, "名字"
      = f.text_field :first_name
    %p
      = f.label :first_name_en, "英文名"
      = f.text_field :first_name_en
    %p
      = f.label :last_name_en, "英文姓"
      = f.text_field :last_name_en
    %p
      = f.label :username, "帳號名稱"
      = f.text_field :username
    %p
      = f.label :email, "電子信箱"
      = f.text_field :email
    %p
      = f.label :password, "密碼 (最少六個字)"
      = f.password_field :password
    / %p
    /   = f.label :password, "確認密碼"
    /   = f.password_field :password_confirmation
    %a.waves-effect.waves-light.btn
      = f.submit

app/views/users/show.html.haml
.white-margin
  .user-page
    .user-page-left
      %section.user-page-left-info
        .user-name
          %h3.font-ch
            =@user.last_name
          %h3.font-ch
            =@user.first_name
        .user-info
          .user-avatar
            =image_tag @user.avatar_url, class: "materialboxed"
            -if @user == current_user
            -elsif @user.followers.include?(current_user)
              = link_to "取消追蹤", unfollow_path(follower: current_user.id, followee: @user.id), method: "delete", class: "btn waves-effect waves-light light-blue"
            -else
              - if current_user
                = link_to "追蹤", follow_path(follower: current_user, followee: @user.id), method: "post", class: "btn waves-effect waves-light light-blue"
              - else 
                = link_to "追蹤", new_user_path, class: "btn waves-effect waves-light light-blue"
          .user-info-right
            .user-info-physical
              -if @user.righthanded
                %p Righthanded
              -else
                %p Lefthanded
              -if @user.double_handed_backhand
                %p Double Handed Backhand
              -else
                %p Single Handed Backhand
              -if @user.height.present?
                %p
                  = @user.height
                  cm
              -else
                %p N/A
              -if @user.weight.present?
                %p
                  = @user.weight
                  kg
              -else
                %p N/A
            .user-info-training
              .training-left
                .user-info-block
                  .training-title
                    %p 球隊/學校:
                  .training-content
                    %p
                      = @user.academy
                .user-info-block
                  .training-title
                    %p 城市:
                  .training-content
                    %p
                      = @user.city
              .training-right
                .user-info-block
                  .user-followers
                    = link_to "追蹤人數", followees_user_path
                    = link_to @user.followees.count, followees_user_path
                .user-info-block
                  .user-followees
                    = link_to "粉絲人數", followers_user_path
                    = link_to @user.followers.count, followers_user_path
        -if @user == current_user
          .waves-effect.waves-light.btn
            =link_to "編輯個人檔案", edit_user_path
            %i.material-icons mode_edit
      %section.user-page-left-athletic
        %ul#tabs-swipe-demo.tabs
          %li.tab.col.s3
            %a{:href => "#test-swipe-1"} 運動
          %li.tab.col.s3
            %a.active{:href => "#test-swipe-2"} 學業
          %li.tab.col.s3
            %a{:href => "#test-swipe-3"} 影片
        #test-swipe-1.col.s12.blue
          .athletic-record
            %p ITF 排名:
            %p
              =@user.itf
          .athletic-record
            %p UTR 級數:
            %p
              =@user.utr
          .athletic-record
            %p 全國 排名:
            %p
              =@user.ntr
        #test-swipe-2.col.s12.pink
          .athletic-record
            %p SAT 成績
            %p
              =@user.sat
          .athletic-record
            %p ACT 成績
            %p
              =@user.act
          .athletic-record
            %p TOEFL 成績
            %p
              =@user.toefl
        #test-swipe-3.col.s12.green
          .video-container
            %iframe{:allowfullscreen => "", :frameborder => "0", :height => "480", :src => "https://www.youtube.com/embed/videoseries?list=PLmVw0Ou6nvAD0SLC2QjXySCgTQur9Xj3r", :width => "853"}
      %section.user-page-left-about
        %h3.section-title.font-en About
        %h3.section-title.font-ch 關於我
        %p
          = @user.about
      %section.user-page-left-tweets
        %h3.section-title.font-ch Posts
        %h3.section-title.font-ch 我的貼文
        %ul
          - @tweets.reverse.each do |tweet|
            %div.follower-href
              = tweet.body
            %li.divider
    .user-page-right
      %div.col.s12
        最近到訪過你的檔案
      -if @user == current_user
        .waves-effect.waves-light.btn
          =link_to "產生客製化信件", email_user_path

app/views/users/update.html.haml
.white-margin
  .user-page
    .user-page-left
      %section.user-page-left-info
        .user-name
          %h3.font-ch 陳漢宇
          %h3.font-en Han-Yu Chen
        .user-info
          .user-avatar
            =image_tag @user.avatar_url
            = form_for @user do |f|
              %p
                = f.label :password, "確認密碼"
                = f.password_field :password_confirmation
              %a.waves-effect.waves-light.btn
                = f.submit
          .user-info-right
            .user-info-physical
              %p Right Handed
              %p 180cm
              %p 78kg
            .user-info-training
              .training-left
                .user-info-block
                  .training-title
                    %p 球隊/學校:
                  .training-content
                    %p 大慶商工
                .user-info-block
                  .training-title
                    %p 城市:
                  .training-content
                    %p 台中
              .training-right
                .user-social
                  .user-followers
                    %p 追蹤人數
                    %p 100
                  .user-followees
                    %p 粉絲
                    %p 5000
      %section.user-page-left-athletic
        %ul#tabs-swipe-demo.tabs
          %li.tab.col.s3
            %a{:href => "#test-swipe-1"} 運動
          %li.tab.col.s3
            %a.active{:href => "#test-swipe-2"} 學業
          %li.tab.col.s3
            %a{:href => "#test-swipe-3"} 影片
        #test-swipe-1.col.s12.blue
          .athletic-record
            %p ITF 排名:
            %p 215
          .athletic-record
            %p UTR 排名:
            %p 10
          .athletic-record
            %p 全國 排名:
            %p 13
        #test-swipe-2.col.s12.pink
          .athletic-record
            %p SAT 成績
            %p 1080
          .athletic-record
            %p TOEFL 成績
            %p 102
        #test-swipe-3.col.s12.green
          .video-container
            %iframe{:allowfullscreen => "", :frameborder => "0", :height => "480", :src => "https://www.youtube.com/embed/videoseries?list=PLmVw0Ou6nvAD0SLC2QjXySCgTQur9Xj3r", :width => "853"}
      %section.user-page-left-about
        關於我
    .user-page-right
      right

app/views/welcome/index.html.haml
.section.welcome
	.container
		-if @user
			-array = []
			-@user.tweets.each do |tweet|
				-array<<tweet
			-@user.followees.each do |followee|
				-followee.tweets.each do |tweet|
					-array<<tweet
			-sorted = array.uniq.sort_by &:created_at
			-sorted = sorted.reverse
			-sorted.each do |tweet|
				.row
					.col.s9
						.card.blue-grey.darken-1
							.card-image
								.col.s3.m3
									%img.responsive-img{:alt => "profile image", :src => "#{tweet.user.avatar_url}"}/
							.card-content.white-text
								%span.card-title
									= link_to tweet.user.last_name + tweet.user.first_name, user_path(tweet.user)

								%p= tweet.body
								%p= tweet.created_at.to_formatted_s(:db)
							.card-action
								%a.btn.waves-effect.waves-light.orange{:href => "/tweets/#{tweet.id}/like"}
									= tweet.likes.count
									Likes
								- if tweet.user.followers.include?(@user)
									= link_to "取消追蹤", unfollow_path(follower: @user.id, followee: tweet.user.id), method: "delete", class: "btn waves-effect waves-light light-blue"
								- elsif tweet.user = @user
								- else
									= link_to "追蹤", follow_path(follower: @user.id, followee: tweet.user.id), method: "delete", class: "btn waves-effect waves-light light-blue"
		-else	